sonar.projectName=LMS Application
sonar.projectVersion=1.0

# Path to sources
sonar.sources=.
sonar.exclusions=**/*.pyc,**/*.xml,**/*.json,frontend-react/build/**,frontend-react/node_modules/**

# Path to tests
sonar.tests=backend-flask/tests,frontend-react/src/__tests__
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx,**/*_test.py,**/test_*.py

# Source encoding
sonar.sourceEncoding=UTF-8

# Python specific
sonar.python.version=3.10
sonar.python.coverage.reportPaths=coverage.xml

# JavaScript specific
sonar.javascript.lcov.reportPaths=frontend-react/coverage/lcov.info

# TypeScript specific
sonar.typescript.tsconfigPath=frontend-react/tsconfig.json