name: Container Security Scan

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scan:
    name: Scan Container Images
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build backend image
        run: |
          docker build -t aqaziuog/lms-backend:local ./backend-flask
          
      - name: Build frontend image
        run: |
          docker build -t aqaziuog/lms-frontend:local ./frontend-react

      - name: Run Trivy vulnerability scanner on backend
        uses: aquasecurity/trivy-action@master
        continue-on-error: true  # This allows the workflow to continue even if this step fails
        with:
            image-ref: 'aqaziuog/lms-backend:local'
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'

      - name: Run Trivy vulnerability scanner on frontend
        uses: aquasecurity/trivy-action@master
        continue-on-error: true  # This allows the workflow to continue even if this step fails

        if: always()  # Run even if backend scan fails
        with:
          image-ref: 'aqaziuog/lms-frontend:local'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
